{
 "title": "Metrics - FluentBit",
 "description": "This is a simple dashboard for Fluent-bit",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Fluent-bit input bytes/s",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 2, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(fluentbit_input_bytes_total[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Fluent-bit output bytes/s",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(fluentbit_output_proc_bytes_total[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Fluent-bit error/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 2, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(fluentbit_output_errors_total[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Fluent-bit retries/fails",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 11, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(fluentbit_output_retries_total[1m])",
     "legendFormat": "Retries {{ pod }}"
    },
    {
     "expr": "rate(fluentbit_output_retries_failed_total[1m])",
     "legendFormat": "Failed {{ pod }}"
    }
   ]
  }
 ]
}